"""
HTML report formatter.
"""

from typing import Dict, Any
from ...core import ScanResult


class HTMLFormatter:
    """Formats scan results as HTML report."""

    def format(self, result: ScanResult) -> str:
        """Format scan result as HTML."""
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Nuvu Scan Report - {result.provider.upper()}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 3px solid #4CAF50; padding-bottom: 10px; }}
        h2 {{ color: #555; margin-top: 30px; }}
        .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }}
        .summary-card {{ background: #f9f9f9; padding: 15px; border-radius: 5px; border-left: 4px solid #4CAF50; }}
        .summary-card h3 {{ margin: 0 0 10px 0; color: #666; font-size: 14px; text-transform: uppercase; }}
        .summary-card .value {{ font-size: 24px; font-weight: bold; color: #333; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #4CAF50; color: white; font-weight: bold; }}
        tr:hover {{ background: #f5f5f5; }}
        .risk-flag {{ display: inline-block; background: #ff4444; color: white; padding: 3px 8px; border-radius: 3px; font-size: 11px; margin: 2px; }}
        .unused {{ color: #ff8800; font-weight: bold; }}
        .no-owner {{ color: #ff4444; font-weight: bold; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Nuvu Scan Report</h1>
        <p><strong>Provider:</strong> {result.provider.upper()}</p>
        <p><strong>Account ID:</strong> {result.account_id}</p>
        <p><strong>Scan Time:</strong> {result.scan_timestamp}</p>
        
        <h2>Executive Summary</h2>
        <div class="summary">
            <div class="summary-card">
                <h3>Total Assets</h3>
                <div class="value">{len(result.assets)}</div>
            </div>
            <div class="summary-card">
                <h3>Estimated Monthly Cost</h3>
                <div class="value">${result.total_cost_estimate_usd:,.2f}</div>
            </div>
            <div class="summary-card">
                <h3>Unused Assets</h3>
                <div class="value">{result.summary.get('unused_count', 0)}</div>
            </div>
            <div class="summary-card">
                <h3>No Owner</h3>
                <div class="value">{result.summary.get('no_owner_count', 0)}</div>
            </div>
            <div class="summary-card">
                <h3>Risky Assets</h3>
                <div class="value">{result.summary.get('risky_count', 0)}</div>
            </div>
        </div>
        
        <h2>Assets by Category</h2>
        <table>
            <tr><th>Category</th><th>Count</th></tr>
"""

        for category, count in result.summary.get("assets_by_category", {}).items():
            html += f"            <tr><td>{category.replace('_', ' ').title()}</td><td>{count}</td></tr>\n"

        html += """        </table>
        
        <h2>All Assets</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Service</th>
                <th>Type</th>
                <th>Region</th>
                <th>Cost (USD/mo)</th>
                <th>Owner</th>
                <th>Risks</th>
            </tr>
"""

        # Sort assets by cost (descending)
        sorted_assets = sorted(result.assets, key=lambda x: x.cost_estimate_usd or 0, reverse=True)

        for asset in sorted_assets:
            owner_class = ""
            if asset.ownership_confidence == "unknown":
                owner_class = "no-owner"

            risk_flags_html = ""
            if asset.risk_flags:
                for flag in asset.risk_flags:
                    risk_flags_html += f'<span class="risk-flag">{flag}</span>'

            html += f"""            <tr>
                <td>{asset.name}</td>
                <td>{asset.service}</td>
                <td>{asset.asset_type}</td>
                <td>{asset.region}</td>
                <td>${asset.cost_estimate_usd or 0:.2f}</td>
                <td class="{owner_class}">{asset.suggested_owner or 'Unknown'}</td>
                <td>{risk_flags_html}</td>
            </tr>
"""

        html += """        </table>
        
        <div class="footer">
            <p>Generated by Nuvu - AWS Data Asset Control</p>
            <p>Visit <a href="https://nuvu.dev">https://nuvu.dev</a> for continuous monitoring</p>
        </div>
    </div>
</body>
</html>"""

        return html
